spring:
  application:
    name: delivery-service

  data:
    mongodb:
      database: delivery

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsDeliveryChanged:
          destination: moments.delivery.changed
          contentType: application/json
  profiles:
    active: ribbon-only
  jpa:
    show-sql: true
server:
  port: 8003

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey
  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33

delivery-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:18081,localhost:28081
    ServerListRefreshInterval: 15000