spring:
  application:
    name: ribbon-server

server:
  port: 8182
  
management:
  security:
    enabled: false

ribbon-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8182,http://localhost:8183
    ServerListRefreshInterval: 15000
